# Generated by Django 6.0.2 on 2026-03-27 18:10

import auth_sys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=auth_sys.models.user_avatar_path, verbose_name='Аватар'),
        ),
    ]
