# Generated by Django 6.0.2 on 2026-03-26 19:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Название')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'verbose_name': 'thread', 'verbose_name_plural': 'threads'},
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Название темы'),
        ),
        migrations.AddField(
            model_name='thread',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.theme', verbose_name='Главная тема'),
        ),
    ]
