# Generated by Django 6.0.2 on 2026-03-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_theme_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(max_length=100, null=True, verbose_name='Описание'),
        ),
    ]
