# Generated by Django 6.0.2 on 2026-03-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_theme_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True, max_length=100, verbose_name='Описание'),
        ),
    ]
